# Generated by Django 5.1.5 on 2025-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Infrastructure', 'Infrastructure'), ('Equipment', 'Equipment'), ('Utility', 'Utility')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Critical', 'Critical')], default='Good', max_length=20)),
                ('purchase_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Use', 'In Use'), ('Under Maintenance', 'Under Maintenance')], default='Active', max_length=30)),
            ],
        ),
    ]
